apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-micro-reactive-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-micro-reactive
  template:
    metadata:
      labels:
        app: api-micro-reactive
    spec:
      containers:
      - name: api-micro-reactive
        image: anchayhua/api-micro-reactive
        ports:
        - containerPort: 8080
